name: ESPHome Build

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ESPHome Firmware
        uses: esphome/build-action@v6
        with:
          yaml-file: esp32_ceshi_device.yaml # 替换为你的实际文件名
          version: latest           # 指定 ESPHome 版本，可选
          complete-manifest: true   # 生成完整的 manifest 文件，便于 web 刷写

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            *.bin
            *.json